# =============================================================================
# DEFAULT IMAGE AND SERVICES
# =============================================================================

default:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind

# =============================================================================
# STAGES
# =============================================================================

stages: [ build, scanning, deploy, web ]

# =============================================================================
# GLOBAL VARIABLES
# =============================================================================

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: none
  GIT_STRATEGY: none
