# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# MYSQL
# =============================================================================

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      TZ: "America/Bahia"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "123456"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - mysql

# =============================================================================
# BACKEND
# =============================================================================

  backend:
    container_name: ${CONTAINER_BACKEND_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE_BACKEND}
      dockerfile: Dockerfile
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - backend

# =============================================================================
# FRONTEND
# =============================================================================

  frontend:
    container_name: ${CONTAINER_FRONTEND_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE_FRONTEND}
      dockerfile: Dockerfile
    environment:
      - CI=true
    restart: unless-stopped
    ports: 
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    depends_on:
      - backend
      - mysql
    networks:
      - frontend

# =============================================================================
# NETWORK
# =============================================================================

networks:
  backend:
  frontend:
  mysql:
