{{- if or (not .Values.allowEmptyRootPassword) (or .Values.mysqlRootPassword .Values.mysqlPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mysql.secret.name" . }}
type: Opaque
data:
  {{- if .Values.mysql.root.password }}
  mysql-root-password: {{ .Values.mysql.root.password | b64enc | quote }}
  {{- else if (not .Values.mysql.root.forcePassword) }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else if (not .Values.mysql.allowEmptyRootPassword) }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ required "A MySQL Root Password is required!" .Values.mysql.root.password }}
  {{- end }}
  {{- if .Values.mysql.db.user }}
  {{- if .Values.mysql.db.password }}
  mysql-password: {{ .Values.mysql.db.password | b64enc | quote }}
  {{- else if (not .Values.mysql.db.forcePassword) }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else if (not .Values.mysql.allowEmptyRootPassword) }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  mysql-password: {{ required "A MySQL Database Password is required!" .Values.mysql.db.password }}
  {{- end }}
  {{- end }}
{{- end }}
---
