apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.metadata.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: {{ include "backend.metadata.name" . }}
    port: {{ .Values.deployment.backend.serviceport }}
    protocol: TCP
    targetPort: {{ .Values.deployment.backend.containerport }}
  selector:
    app: {{ include "backend.metadata.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.metadata.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: {{ include "frontend.metadata.name" . }}
    port: {{ .Values.deployment.frontend.serviceport }}
    protocol: TCP
    targetPort: {{ .Values.deployment.frontend.containerport }}
  selector:
    app: {{ include "frontend.metadata.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.mysql.name }}
    port: {{ .Values.mysql.service.port }}
    protocol: TCP
    targetPort: {{ .Values.mysql.service.port }}
  selector:
    app: {{ .Values.mysql.name }}
---
